import { Ejercicio } from '@/lib/tipos';

export const ejerciciosSeed: Omit<Ejercicio, 'id' | 'creado_en'>[] = [
  // PECHO
  {
    seed_id: 'press-banca-plano',
    nombre: 'Press banca plano',
    grupo_muscular: 'Pecho',
    grupo_secundario: ['Hombros', 'Tríceps'],
    tipo_ejercicio: 'compound',
    equipamiento: 'Barra',
    es_seedeado: true,
  },
  {
    seed_id: 'svend-press',
    nombre: 'Svend press',
    grupo_muscular: 'Pecho',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Mancuernas',
    es_seedeado: true,
  },
  {
    seed_id: 'press-banca-declinado',
    nombre: 'Press banca declinado',
    grupo_muscular: 'Pecho',
    grupo_secundario: ['Tríceps'],
    tipo_ejercicio: 'compound',
    equipamiento: 'Barra',
    es_seedeado: true,
  },
  {
    seed_id: 'press-banca-inclinado',
    nombre: 'Press banca inclinado',
    grupo_muscular: 'Pecho',
    grupo_secundario: ['Hombros', 'Tríceps'],
    tipo_ejercicio: 'compound',
    equipamiento: 'Barra',
    es_seedeado: true,
  },
  {
    seed_id: 'aperturas-maquina',
    nombre: 'Aperturas en máquina',
    grupo_muscular: 'Pecho',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Máquina',
    es_seedeado: true,
  },

  // ESPALDA
  {
    seed_id: 'remo-gironda',
    nombre: 'Remo Gironda',
    grupo_muscular: 'Espalda',
    grupo_secundario: ['Bíceps'],
    tipo_ejercicio: 'compound',
    equipamiento: 'Máquina',
    es_seedeado: true,
  },
  {
    seed_id: 'remo-unilateral',
    nombre: 'Remo unilateral',
    grupo_muscular: 'Espalda',
    grupo_secundario: ['Bíceps'],
    tipo_ejercicio: 'compound',
    equipamiento: 'Mancuernas',
    es_seedeado: true,
  },
  {
    seed_id: 'jalon-prono',
    nombre: 'Jalón al pecho — agarre prono',
    grupo_muscular: 'Espalda',
    grupo_secundario: ['Bíceps'],
    tipo_ejercicio: 'compound',
    equipamiento: 'Cables',
    es_seedeado: true,
  },
  {
    seed_id: 'jalon-neutro-supino',
    nombre: 'Jalón al pecho — agarre neutro/supino',
    grupo_muscular: 'Espalda',
    grupo_secundario: ['Bíceps'],
    tipo_ejercicio: 'compound',
    equipamiento: 'Cables',
    es_seedeado: true,
  },

  // HOMBROS
  {
    seed_id: 'elevaciones-laterales',
    nombre: 'Elevaciones laterales',
    grupo_muscular: 'Hombros',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Mancuernas',
    es_seedeado: true,
  },
  {
    seed_id: 'face-pull',
    nombre: 'Face Pull',
    grupo_muscular: 'Hombros',
    grupo_secundario: ['Espalda'],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Cables',
    es_seedeado: true,
  },
  {
    seed_id: 'elevaciones-frontales',
    nombre: 'Elevaciones frontales',
    grupo_muscular: 'Hombros',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Barra',
    es_seedeado: true,
  },
  {
    seed_id: 'landmine-180',
    nombre: 'Landmine 180',
    grupo_muscular: 'Hombros',
    grupo_secundario: ['Pecho'],
    tipo_ejercicio: 'compound',
    equipamiento: 'Barra',
    notas: 'Realizar por lado (ambos lados cuentan como una serie)',
    es_seedeado: true,
  },

  // BÍCEPS / ANTEBRAZO
  {
    seed_id: 'curl-biceps',
    nombre: 'Curl de bíceps',
    grupo_muscular: 'Bíceps',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Barra',
    es_seedeado: true,
  },
  {
    seed_id: 'curl-martillo',
    nombre: 'Curl martillo',
    grupo_muscular: 'Bíceps',
    grupo_secundario: ['Antebrazo'],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Mancuernas',
    es_seedeado: true,
  },
  {
    seed_id: 'curl-inverso-barra',
    nombre: 'Curl inverso con barra',
    grupo_muscular: 'Antebrazo',
    grupo_secundario: ['Bíceps'],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Barra',
    es_seedeado: true,
  },
  {
    seed_id: 'curl-muñeca',
    nombre: 'Curl de muñeca',
    grupo_muscular: 'Antebrazo',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Barra',
    es_seedeado: true,
  },

  // TRÍCEPS
  {
    seed_id: 'extension-triceps-unilateral',
    nombre: 'Extensión de tríceps unilateral en polea',
    grupo_muscular: 'Tríceps',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Cables',
    es_seedeado: true,
  },
  {
    seed_id: 'extension-triceps-cuerda',
    nombre: 'Extensión de tríceps tras nuca con cuerda',
    grupo_muscular: 'Tríceps',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Cables',
    es_seedeado: true,
  },

  // PIERNAS / GLÚTEOS
  {
    seed_id: 'sentadilla',
    nombre: 'Sentadilla',
    grupo_muscular: 'Piernas',
    grupo_secundario: ['Glúteos'],
    tipo_ejercicio: 'compound',
    equipamiento: 'Barra',
    es_seedeado: true,
  },
  {
    seed_id: 'peso-muerto-rumano',
    nombre: 'Peso muerto rumano (PMR)',
    grupo_muscular: 'Piernas',
    grupo_secundario: ['Espalda', 'Glúteos'],
    tipo_ejercicio: 'compound',
    equipamiento: 'Barra',
    es_seedeado: true,
  },
  {
    seed_id: 'prensa',
    nombre: 'Prensa',
    grupo_muscular: 'Piernas',
    grupo_secundario: ['Glúteos'],
    tipo_ejercicio: 'compound',
    equipamiento: 'Máquina',
    es_seedeado: true,
  },
  {
    seed_id: 'curl-femoral',
    nombre: 'Curl femoral',
    grupo_muscular: 'Piernas',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Máquina',
    es_seedeado: true,
  },
  {
    seed_id: 'hip-thrust',
    nombre: 'Hip thrust',
    grupo_muscular: 'Glúteos',
    grupo_secundario: ['Piernas'],
    tipo_ejercicio: 'compound',
    equipamiento: 'Barra',
    es_seedeado: true,
  },
  {
    seed_id: 'extension-cuadriceps',
    nombre: 'Extensión de cuádriceps',
    grupo_muscular: 'Piernas',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Máquina',
    es_seedeado: true,
  },
  {
    seed_id: 'patada-gluteos',
    nombre: 'Patada de glúteos',
    grupo_muscular: 'Glúteos',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Cables',
    es_seedeado: true,
  },
  {
    seed_id: 'gemelos',
    nombre: 'Gemelos',
    grupo_muscular: 'Piernas',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Máquina',
    es_seedeado: true,
  },
  {
    seed_id: 'abductores',
    nombre: 'Abductores',
    grupo_muscular: 'Piernas',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Máquina',
    es_seedeado: true,
  },
  {
    seed_id: 'aductores',
    nombre: 'Aductores',
    grupo_muscular: 'Piernas',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Máquina',
    es_seedeado: true,
  },

  // ABDOMINALES
  {
    seed_id: 'crunch-polea',
    nombre: 'Crunch en polea',
    grupo_muscular: 'Abdominales',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Cables',
    es_seedeado: true,
  },
  {
    seed_id: 'elevaciones-piernas-banco',
    nombre: 'Elevaciones de piernas en banco inclinado',
    grupo_muscular: 'Abdominales',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Banco',
    es_seedeado: true,
  },
  {
    seed_id: 'ab-wheel',
    nombre: 'Ab wheel',
    grupo_muscular: 'Abdominales',
    grupo_secundario: [],
    tipo_ejercicio: 'isolation',
    equipamiento: 'Cuerpo',
    es_seedeado: true,
  },
];